# Generated by Django 5.2.8 on 2025-12-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
